# Generated by Django 4.1.5 on 2023-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('img1', models.ImageField(upload_to='noticias')),
                ('img2', models.ImageField(null=True, upload_to='noticias')),
                ('img3', models.ImageField(null=True, upload_to='noticias')),
                ('img4', models.ImageField(null=True, upload_to='noticias')),
            ],
        ),
    ]
