# Generated by Django 4.1.5 on 2023-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
    ]
