# Generated by Django 4.1.5 on 2023-02-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticia_img3_alter_noticia_img4'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
    ]
